using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Autodesk.Revit.DB;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO.Compression;

namespace RevitShortcuts.Services
{
    /// <summary>
    /// Service for exporting QA reports in multiple formats
    /// </summary>
    public class ReportExportService
    {
        private readonly Document _doc;
        private readonly ModelHealthSummary _summary;

        public ReportExportService(Document doc, ModelHealthSummary summary)
        {
            _doc = doc;
            _summary = summary;

            // Set EPPlus license context
            ExcelPackage.LicenseContext = LicenseContext.NonCommercial;
        }

        #region Excel Export

        public void ExportToExcel(string filePath)
        {
            using (var package = new ExcelPackage())
            {
                // Summary sheet
                CreateSummarySheet(package);

                // Detailed findings sheet
                CreateDetailedFindingsSheet(package);

                // Issues by category
                CreateCategoryBreakdownSheet(package);

                // Element list (for affected elements)
                CreateAffectedElementsSheet(package);

                // Metrics sheet
                CreateMetricsSheet(package);

                package.SaveAs(new FileInfo(filePath));
            }
        }

        private void CreateSummarySheet(ExcelPackage package)
        {
            var worksheet = package.Workbook.Worksheets.Add("Summary");

            // Header
            worksheet.Cells["A1"].Value = "Model Health Report - Summary";
            worksheet.Cells["A1:F1"].Merge = true;
            worksheet.Cells["A1"].Style.Font.Size = 18;
            worksheet.Cells["A1"].Style.Font.Bold = true;
            worksheet.Cells["A1"].Style.HorizontalAlignment = ExcelHorizontalAlignment.Center;

            int row = 3;

            // Project Info
            worksheet.Cells[row, 1].Value = "Project Information";
            worksheet.Cells[row, 1].Style.Font.Bold = true;
            worksheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            worksheet.Cells[row, 1].Value = "Project Name:";
            worksheet.Cells[row, 2].Value = _summary.ProjectName;
            row++;

            worksheet.Cells[row, 1].Value = "File Path:";
            worksheet.Cells[row, 2].Value = _summary.FilePath;
            row++;

            worksheet.Cells[row, 1].Value = "File Size (MB):";
            worksheet.Cells[row, 2].Value = _summary.FileSizeMB;
            worksheet.Cells[row, 2].Style.Numberformat.Format = "#,##0.00";
            row++;

            worksheet.Cells[row, 1].Value = "Generated Date:";
            worksheet.Cells[row, 2].Value = _summary.GeneratedDate;
            worksheet.Cells[row, 2].Style.Numberformat.Format = "yyyy-mm-dd hh:mm:ss";
            row++;

            worksheet.Cells[row, 1].Value = "Generated By:";
            worksheet.Cells[row, 2].Value = _summary.GeneratedBy;
            row += 2;

            // Quality Score
            worksheet.Cells[row, 1].Value = "Quality Score";
            worksheet.Cells[row, 1].Style.Font.Bold = true;
            worksheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            worksheet.Cells[row, 1].Value = "Overall Score:";
            worksheet.Cells[row, 2].Value = _summary.OverallQualityScore;
            worksheet.Cells[row, 2].Style.Numberformat.Format = "0.00";
            worksheet.Cells[row, 2].Style.Font.Size = 16;
            worksheet.Cells[row, 2].Style.Font.Bold = true;
            row++;

            worksheet.Cells[row, 1].Value = "Grade:";
            worksheet.Cells[row, 2].Value = _summary.QualityGrade;
            worksheet.Cells[row, 2].Style.Font.Size = 16;
            worksheet.Cells[row, 2].Style.Font.Bold = true;
            SetGradeColor(worksheet.Cells[row, 2], _summary.QualityGrade);
            row += 2;

            // Statistics
            worksheet.Cells[row, 1].Value = "Check Statistics";
            worksheet.Cells[row, 1].Style.Font.Bold = true;
            worksheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var stats = new Dictionary<string, int>
            {
                { "Total Checks", _summary.TotalChecks },
                { "Passed", _summary.PassedChecks },
                { "Failed", _summary.FailedChecks },
                { "Total Issues", _summary.TotalIssues },
                { "Critical Issues", _summary.CriticalIssues },
                { "Errors", _summary.ErrorIssues },
                { "Warnings", _summary.WarningIssues },
                { "Info", _summary.InfoIssues }
            };

            foreach (var stat in stats)
            {
                worksheet.Cells[row, 1].Value = stat.Key + ":";
                worksheet.Cells[row, 2].Value = stat.Value;
                row++;
            }

            row += 2;

            // Model Metrics
            worksheet.Cells[row, 1].Value = "Model Metrics";
            worksheet.Cells[row, 1].Style.Font.Bold = true;
            worksheet.Cells[row, 1].Style.Font.Size = 14;
            row += 2;

            var metrics = new Dictionary<string, int>
            {
                { "Total Elements", _summary.TotalElements },
                { "Total Views", _summary.TotalViews },
                { "Total Sheets", _summary.TotalSheets },
                { "Total Families", _summary.TotalFamilies },
                { "Total Warnings", _summary.TotalWarnings }
            };

            foreach (var metric in metrics)
            {
                worksheet.Cells[row, 1].Value = metric.Key + ":";
                worksheet.Cells[row, 2].Value = metric.Value;
                worksheet.Cells[row, 2].Style.Numberformat.Format = "#,##0";
                row++;
            }

            worksheet.Cells.AutoFitColumns();
        }

        private void CreateDetailedFindingsSheet(ExcelPackage package)
        {
            var worksheet = package.Workbook.Worksheets.Add("Detailed Findings");

            // Headers
            worksheet.Cells[1, 1].Value = "Category";
            worksheet.Cells[1, 2].Value = "Check Name";
            worksheet.Cells[1, 3].Value = "Status";
            worksheet.Cells[1, 4].Value = "Severity";
            worksheet.Cells[1, 5].Value = "Issue Count";
            worksheet.Cells[1, 6].Value = "Message";
            worksheet.Cells[1, 7].Value = "Details";
            worksheet.Cells[1, 8].Value = "Recommended Fix";

            // Style headers
            using (var range = worksheet.Cells[1, 1, 1, 8])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(79, 129, 189));
                range.Style.Font.Color.SetColor(System.Drawing.Color.White);
            }

            int row = 2;

            foreach (var category in _summary.Categories)
            {
                foreach (var result in category.Results)
                {
                    worksheet.Cells[row, 1].Value = category.CategoryName;
                    worksheet.Cells[row, 2].Value = result.CheckName;
                    worksheet.Cells[row, 3].Value = result.Passed ? "PASS" : "FAIL";
                    worksheet.Cells[row, 4].Value = result.Severity.ToString();
                    worksheet.Cells[row, 5].Value = result.IssueCount;
                    worksheet.Cells[row, 6].Value = result.Message;
                    worksheet.Cells[row, 7].Value = result.Details;
                    worksheet.Cells[row, 8].Value = result.RecommendedFix;

                    // Color code status
                    if (!result.Passed)
                    {
                        worksheet.Cells[row, 3].Style.Fill.PatternType = ExcelFillStyle.Solid;
                        worksheet.Cells[row, 3].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(255, 199, 206));
                    }
                    else
                    {
                        worksheet.Cells[row, 3].Style.Fill.PatternType = ExcelFillStyle.Solid;
                        worksheet.Cells[row, 3].Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(198, 239, 206));
                    }

                    row++;
                }
            }

            worksheet.Cells.AutoFitColumns();
        }

        private void CreateCategoryBreakdownSheet(ExcelPackage package)
        {
            var worksheet = package.Workbook.Worksheets.Add("Category Breakdown");

            // Headers
            worksheet.Cells[1, 1].Value = "Category";
            worksheet.Cells[1, 2].Value = "Total Checks";
            worksheet.Cells[1, 3].Value = "Passed";
            worksheet.Cells[1, 4].Value = "Failed";
            worksheet.Cells[1, 5].Value = "Total Issues";
            worksheet.Cells[1, 6].Value = "Pass Rate %";

            // Style headers
            using (var range = worksheet.Cells[1, 1, 1, 6])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(79, 129, 189));
                range.Style.Font.Color.SetColor(System.Drawing.Color.White);
            }

            int row = 2;

            foreach (var category in _summary.Categories)
            {
                int totalChecks = category.Results.Count;
                double passRate = totalChecks > 0 ? (double)category.PassedCount / totalChecks * 100 : 0;

                worksheet.Cells[row, 1].Value = category.CategoryName;
                worksheet.Cells[row, 2].Value = totalChecks;
                worksheet.Cells[row, 3].Value = category.PassedCount;
                worksheet.Cells[row, 4].Value = category.FailedCount;
                worksheet.Cells[row, 5].Value = category.TotalIssues;
                worksheet.Cells[row, 6].Value = passRate;
                worksheet.Cells[row, 6].Style.Numberformat.Format = "0.00";

                row++;
            }

            worksheet.Cells.AutoFitColumns();
        }

        private void CreateAffectedElementsSheet(ExcelPackage package)
        {
            var worksheet = package.Workbook.Worksheets.Add("Affected Elements");

            // Headers
            worksheet.Cells[1, 1].Value = "Category";
            worksheet.Cells[1, 2].Value = "Check Name";
            worksheet.Cells[1, 3].Value = "Element IDs";

            using (var range = worksheet.Cells[1, 1, 1, 3])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(79, 129, 189));
                range.Style.Font.Color.SetColor(System.Drawing.Color.White);
            }

            int row = 2;

            foreach (var category in _summary.Categories)
            {
                foreach (var result in category.Results.Where(r => r.AffectedElements?.Count > 0))
                {
                    worksheet.Cells[row, 1].Value = category.CategoryName;
                    worksheet.Cells[row, 2].Value = result.CheckName;
                    worksheet.Cells[row, 3].Value = string.Join(", ", result.AffectedElements.Select(id => id.IntegerValue));
                    row++;
                }
            }

            worksheet.Cells.AutoFitColumns();
        }

        private void CreateMetricsSheet(ExcelPackage package)
        {
            var worksheet = package.Workbook.Worksheets.Add("Metrics");

            worksheet.Cells[1, 1].Value = "Check Name";
            worksheet.Cells[1, 2].Value = "Metric Key";
            worksheet.Cells[1, 3].Value = "Metric Value";

            using (var range = worksheet.Cells[1, 1, 1, 3])
            {
                range.Style.Font.Bold = true;
                range.Style.Fill.PatternType = ExcelFillStyle.Solid;
                range.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(79, 129, 189));
                range.Style.Font.Color.SetColor(System.Drawing.Color.White);
            }

            int row = 2;

            foreach (var category in _summary.Categories)
            {
                foreach (var result in category.Results.Where(r => r.Metrics?.Count > 0))
                {
                    foreach (var metric in result.Metrics)
                    {
                        worksheet.Cells[row, 1].Value = result.CheckName;
                        worksheet.Cells[row, 2].Value = metric.Key;
                        worksheet.Cells[row, 3].Value = metric.Value?.ToString();
                        row++;
                    }
                }
            }

            worksheet.Cells.AutoFitColumns();
        }

        private void SetGradeColor(ExcelRange cell, string grade)
        {
            cell.Style.Fill.PatternType = ExcelFillStyle.Solid;
            switch (grade)
            {
                case "A":
                    cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(0, 176, 80));
                    cell.Style.Font.Color.SetColor(System.Drawing.Color.White);
                    break;
                case "B":
                    cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(146, 208, 80));
                    break;
                case "C":
                    cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(255, 217, 102));
                    break;
                case "D":
                    cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(255, 153, 0));
                    break;
                case "F":
                    cell.Style.Fill.BackgroundColor.SetColor(System.Drawing.Color.FromArgb(255, 0, 0));
                    cell.Style.Font.Color.SetColor(System.Drawing.Color.White);
                    break;
            }
        }

        #endregion

        #region PDF Export

        public void ExportToPDF(string filePath)
        {
            Document pdfDoc = new Document(PageSize.A4);
            PdfWriter.GetInstance(pdfDoc, new FileStream(filePath, FileMode.Create));
            pdfDoc.Open();

            // Title
            var titleFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 24);
            var title = new Paragraph("Model Health Report", titleFont);
            title.Alignment = Element.ALIGN_CENTER;
            pdfDoc.Add(title);

            pdfDoc.Add(new Paragraph("\n"));

            // Project Info
            var headerFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 14);
            var normalFont = FontFactory.GetFont(FontFactory.HELVETICA, 10);

            pdfDoc.Add(new Paragraph("Project Information", headerFont));
            pdfDoc.Add(new Paragraph($"Project: {_summary.ProjectName}", normalFont));
            pdfDoc.Add(new Paragraph($"File Size: {_summary.FileSizeMB:F2} MB", normalFont));
            pdfDoc.Add(new Paragraph($"Date: {_summary.GeneratedDate:yyyy-MM-dd HH:mm:ss}", normalFont));
            pdfDoc.Add(new Paragraph($"Generated By: {_summary.GeneratedBy}", normalFont));
            pdfDoc.Add(new Paragraph("\n"));

            // Quality Score
            pdfDoc.Add(new Paragraph("Quality Score", headerFont));
            var scoreFont = FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 18);
            pdfDoc.Add(new Paragraph($"Score: {_summary.OverallQualityScore:F1} / 100 (Grade: {_summary.QualityGrade})", scoreFont));
            pdfDoc.Add(new Paragraph("\n"));

            // Summary Statistics
            pdfDoc.Add(new Paragraph("Summary Statistics", headerFont));
            PdfPTable statsTable = new PdfPTable(2);
            statsTable.WidthPercentage = 100;

            AddTableRow(statsTable, "Total Checks", _summary.TotalChecks.ToString());
            AddTableRow(statsTable, "Passed", _summary.PassedChecks.ToString());
            AddTableRow(statsTable, "Failed", _summary.FailedChecks.ToString());
            AddTableRow(statsTable, "Critical Issues", _summary.CriticalIssues.ToString());
            AddTableRow(statsTable, "Errors", _summary.ErrorIssues.ToString());
            AddTableRow(statsTable, "Warnings", _summary.WarningIssues.ToString());

            pdfDoc.Add(statsTable);
            pdfDoc.Add(new Paragraph("\n"));

            // Category Breakdown
            pdfDoc.Add(new Paragraph("Category Breakdown", headerFont));
            PdfPTable catTable = new PdfPTable(4);
            catTable.WidthPercentage = 100;

            // Headers
            AddTableCell(catTable, "Category", true);
            AddTableCell(catTable, "Passed", true);
            AddTableCell(catTable, "Failed", true);
            AddTableCell(catTable, "Issues", true);

            foreach (var category in _summary.Categories)
            {
                AddTableCell(catTable, category.CategoryName, false);
                AddTableCell(catTable, category.PassedCount.ToString(), false);
                AddTableCell(catTable, category.FailedCount.ToString(), false);
                AddTableCell(catTable, category.TotalIssues.ToString(), false);
            }

            pdfDoc.Add(catTable);
            pdfDoc.Add(new Paragraph("\n"));

            // Failed Checks Detail
            pdfDoc.Add(new Paragraph("Failed Checks - Details", headerFont));

            foreach (var category in _summary.Categories)
            {
                var failedChecks = category.Results.Where(r => !r.Passed).ToList();
                if (failedChecks.Any())
                {
                    pdfDoc.Add(new Paragraph($"\n{category.CategoryName}", FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 12)));

                    foreach (var check in failedChecks)
                    {
                        pdfDoc.Add(new Paragraph($"  • {check.CheckName} ({check.Severity})", normalFont));
                        pdfDoc.Add(new Paragraph($"    {check.Message}", normalFont));
                        if (!string.IsNullOrEmpty(check.RecommendedFix))
                        {
                            pdfDoc.Add(new Paragraph($"    Fix: {check.RecommendedFix}", FontFactory.GetFont(FontFactory.HELVETICA_OBLIQUE, 9)));
                        }
                    }
                }
            }

            pdfDoc.Close();
        }

        private void AddTableRow(PdfPTable table, string label, string value)
        {
            var cellLabel = new PdfPCell(new Phrase(label, FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10)));
            cellLabel.Border = Rectangle.NO_BORDER;
            cellLabel.Padding = 5;
            table.AddCell(cellLabel);

            var cellValue = new PdfPCell(new Phrase(value, FontFactory.GetFont(FontFactory.HELVETICA, 10)));
            cellValue.Border = Rectangle.NO_BORDER;
            cellValue.Padding = 5;
            table.AddCell(cellValue);
        }

        private void AddTableCell(PdfPTable table, string text, bool isHeader)
        {
            var font = isHeader
                ? FontFactory.GetFont(FontFactory.HELVETICA_BOLD, 10)
                : FontFactory.GetFont(FontFactory.HELVETICA, 9);

            var cell = new PdfPCell(new Phrase(text, font));
            cell.Padding = 5;

            if (isHeader)
            {
                cell.BackgroundColor = new BaseColor(79, 129, 189);
                cell.HorizontalAlignment = Element.ALIGN_CENTER;
            }

            table.AddCell(cell);
        }

        #endregion

        #region JSON Export

        public void ExportToJSON(string filePath)
        {
            var settings = new JsonSerializerSettings
            {
                Formatting = Formatting.Indented,
                NullValueHandling = NullValueHandling.Ignore
            };

            var json = JsonConvert.SerializeObject(_summary, settings);
            File.WriteAllText(filePath, json);
        }

        #endregion

        #region BCF Export

        public void ExportToBCF(string filePath)
        {
            // BCF (BIM Collaboration Format) is a ZIP-based format
            // This is a simplified implementation - full BCF would require more detail

            string tempDir = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString());
            Directory.CreateDirectory(tempDir);

            try
            {
                // Create BCF structure
                CreateBCFMarkup(tempDir);
                CreateBCFProject(tempDir);

                // Create issues for failed checks
                int issueIndex = 1;
                foreach (var category in _summary.Categories)
                {
                    foreach (var result in category.Results.Where(r => !r.Passed))
                    {
                        CreateBCFIssue(tempDir, result, category.CategoryName, issueIndex++);
                    }
                }

                // Zip the folder
                if (File.Exists(filePath))
                    File.Delete(filePath);

                ZipFile.CreateFromDirectory(tempDir, filePath);
            }
            finally
            {
                if (Directory.Exists(tempDir))
                    Directory.Delete(tempDir, true);
            }
        }

        private void CreateBCFProject(string tempDir)
        {
            var projectXml = $@"<?xml version=""1.0"" encoding=""UTF-8""?>
<ProjectExtension>
    <Project ProjectId=""{Guid.NewGuid()}"">
        <Name>{_summary.ProjectName}</Name>
    </Project>
</ProjectExtension>";

            File.WriteAllText(Path.Combine(tempDir, "project.bcfp"), projectXml);
        }

        private void CreateBCFMarkup(string tempDir)
        {
            var versionXml = @"<?xml version=""1.0"" encoding=""UTF-8""?>
<Version VersionId=""2.1"">
    <DetailedVersion>2.1</DetailedVersion>
</Version>";

            File.WriteAllText(Path.Combine(tempDir, "bcf.version"), versionXml);
        }

        private void CreateBCFIssue(string tempDir, QACheckResult result, string category, int index)
        {
            string issueGuid = Guid.NewGuid().ToString();
            string issueDir = Path.Combine(tempDir, issueGuid);
            Directory.CreateDirectory(issueDir);

            var markupXml = $@"<?xml version=""1.0"" encoding=""UTF-8""?>
<Markup>
    <Header>
        <File IfcProject=""{_doc.ProjectInformation.UniqueId}"" />
        <Date>{DateTime.Now:yyyy-MM-ddTHH:mm:ss}</Date>
        <Author>{_summary.GeneratedBy}</Author>
    </Header>
    <Topic Guid=""{issueGuid}"" TopicType=""{result.Severity}"">
        <Title>{result.CheckName}</Title>
        <Priority>{GetBCFPriority(result.Severity)}</Priority>
        <Index>{index}</Index>
        <Labels>{category}</Labels>
        <CreationDate>{DateTime.Now:yyyy-MM-ddTHH:mm:ss}</CreationDate>
        <CreationAuthor>{_summary.GeneratedBy}</CreationAuthor>
        <Description>{result.Message}</Description>
    </Topic>
    <Comment Guid=""{Guid.NewGuid()}"">
        <Date>{DateTime.Now:yyyy-MM-ddTHH:mm:ss}</Date>
        <Author>{_summary.GeneratedBy}</Author>
        <Comment>Issue Count: {result.IssueCount}</Comment>
    </Comment>";

            if (!string.IsNullOrEmpty(result.RecommendedFix))
            {
                markupXml += $@"
    <Comment Guid=""{Guid.NewGuid()}"">
        <Date>{DateTime.Now:yyyy-MM-ddTHH:mm:ss}</Date>
        <Author>System</Author>
        <Comment>Recommended Fix: {result.RecommendedFix}</Comment>
    </Comment>";
            }

            markupXml += "\n</Markup>";

            File.WriteAllText(Path.Combine(issueDir, "markup.bcf"), markupXml);
        }

        private string GetBCFPriority(IssueSeverity severity)
        {
            switch (severity)
            {
                case IssueSeverity.Critical:
                    return "Critical";
                case IssueSeverity.Error:
                    return "Major";
                case IssueSeverity.Warning:
                    return "Normal";
                case IssueSeverity.Info:
                    return "Minor";
                default:
                    return "Normal";
            }
        }

        #endregion
    }
}
